---
configs:
  ccloud_configs:
    api_key: "env::CCLOUD_API_KEY"
    api_secret: "env::CCLOUD_API_SECRET"
    ccloud_user: "env::CONFLUENT_CLOUD_EMAIL"
    ccloud_password: "env::CONFLUENT_CLOUD_PASSWORD"
    # enable_sa_cleanup: true
    detect_ignore_ccloud_internal_accounts: true
    ignore_service_account_list:
      - sa-xxxxx
      - sa-yyyyy
  secret_store:
    enabled: true
    type: aws-secretsmanager
    prefix: ""
    separator: "/"
    rest_proxy_secret_name: "rest_proxy_kafka_users"
    configs:
      - region_name: "region_name"
      - aws_access_key_id: "aws_access_key"
      - aws_secret_access_key: "aws_secret_access_key"
      # - aws_session_token: ""
      # - config:
      #     - read_timeout: 45
      #     # - signature_version: "v4"
